World: world

Team:
  RED:
    DisplayName: RED
    Team:
      ID: 1
      Color : RED
    BossBarColor: RED
    DefaultSiteID: 1
  BLUE:
    DisplayName: BLUE
    Team:
      ID: 2
      Color : BLUE
    BossBarColor: BLUE
    DefaultSiteID: 2

Site:
  1:
    Core: [6,-24,95]
    Generator: [0,59,0]
    MasterSpawnPoint: 0
  2:
    Core: [6,-23,-81]
    Generator: [1,59,1]
    MasterSpawnPoint: 6

Core:
  Material: EMERALD_BLOCK
  Health: 100


PrepareTime: 60

Border:
  +X: 54
  -X: -42
  +Z: 34
  -Z: -18
  +y: -2
  -y: -53

SpawnScoreMax: 200
SpawnScoreThreshold: 100

SpawnPoint:
  0: ['1', '2']
  1: ['0', '3']
  2: ['0', '3']
  3: ['1', '2', '4', '5']
  4: ['3', '6']
  5: ['3', '6']
  6: ['4', '5']

SpawnPointLocation:
  0: [6, -4, 96]
  1: [-3, -37, 38]
  2: [15, -37, 38]
  3: [7, -35, 8]
  4: [-3, -37, -22]
  5: [15, -37, -22]
  6: [6, -3, -81]

SpawnPointCUI:
  1:
    - '    [4]   [5]'
    - '      \  /'
    - '     　[3]'
    - '      /  \'
    - '    [1]   [2]'
  2:
    - '    [2]   [1]'
    - '      \  /'
    - '     　[3]'
    - '      /  \'
    - '    [5]   [4]'
